CREATE TABLE INGREDIENTE
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(250) NOT NULL,
    cantidad bigint  NOT NULL,
    precio numeric(18,2) NOT NULL,
    tipo character varying(50) NOT NULL,
    CONSTRAINT "INGREDIENTE_pkey" PRIMARY KEY (id)
);

INSERT INTO ingrediente(nombre, cantidad, precio, tipo)	VALUES ('Fresa', 20, 50, 'FRUTA');
INSERT INTO ingrediente(nombre, cantidad, precio, tipo)	VALUES ('Pera', 7, 1200, 'FRUTA');
INSERT INTO ingrediente(nombre, cantidad, precio, tipo)	VALUES ('Papaya', 8, 4500, 'FRUTA');
INSERT INTO ingrediente(nombre, cantidad, precio, tipo)	VALUES ('Uvas', 200, 3200, 'FRUTA');
INSERT INTO ingrediente(nombre, cantidad, precio, tipo)	VALUES ('Cebolla', 5, 1350, 'VEGETAL');
INSERT INTO ingrediente(nombre, cantidad, precio, tipo)	VALUES ('Brocoli', 14, 2300, 'VEGETAL');
INSERT INTO ingrediente(nombre, cantidad, precio, tipo)	VALUES ('Pollo', 8, 9500, 'PROTEINA');
INSERT INTO ingrediente(nombre, cantidad, precio, tipo)	VALUES ('Frijol', 12, 2950, 'GRANO');